lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%' # Facultatif, mais recommandé si vous utilisez une clé privée avec phrase secrète
    token_ttl: 3600                    # Durée de vie du token en secondes (1 heure par défaut)
    user_id_claim: email         # Le nom du champ utilisé pour identifier l'utilisateur dans le JWT